// FleetOps rollout health contract, v1.
//
// One unary RolloutService.GetWaveHealth answers the question a canary gate asks: how
// healthy is a given wave of a given rollout right now, and on how much evidence. The
// response carries the measured success ratio and sample size together with the window the
// samples were read from and the thresholds the verdict was computed against, so a caller
// never has to guess which configuration produced a number.
//
// This package is a different bounded context from the agent transport: an operator health
// query is not an agent exchange, and messages are never shared across the two packages.
//
// v1 freezes when it lands: evolve by adding fields, messages, and RPCs only. Never
// renumber, reuse, or rewrite an existing field.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: rollout/v1/rollout.proto

package rolloutv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WaveHealthVerdict is the closed set of outcomes one evaluation can report. A window with
// fewer samples than the configured minimum is undecided rather than healthy, so thin
// evidence can never promote a wave and a waiting gate is distinguishable from a rollback.
type WaveHealthVerdict int32

const (
	// Unset; never sent on a served response.
	WaveHealthVerdict_WAVE_HEALTH_VERDICT_UNSPECIFIED WaveHealthVerdict = 0
	// The window holds too few samples for a decision; the ratio is not promotion evidence.
	WaveHealthVerdict_WAVE_HEALTH_VERDICT_UNDECIDED WaveHealthVerdict = 1
	// The window holds enough samples and the success ratio is at or above the minimum.
	WaveHealthVerdict_WAVE_HEALTH_VERDICT_HEALTHY WaveHealthVerdict = 2
	// The window holds enough samples and the success ratio is below the minimum.
	WaveHealthVerdict_WAVE_HEALTH_VERDICT_UNHEALTHY WaveHealthVerdict = 3
)

// Enum value maps for WaveHealthVerdict.
var (
	WaveHealthVerdict_name = map[int32]string{
		0: "WAVE_HEALTH_VERDICT_UNSPECIFIED",
		1: "WAVE_HEALTH_VERDICT_UNDECIDED",
		2: "WAVE_HEALTH_VERDICT_HEALTHY",
		3: "WAVE_HEALTH_VERDICT_UNHEALTHY",
	}
	WaveHealthVerdict_value = map[string]int32{
		"WAVE_HEALTH_VERDICT_UNSPECIFIED": 0,
		"WAVE_HEALTH_VERDICT_UNDECIDED":   1,
		"WAVE_HEALTH_VERDICT_HEALTHY":     2,
		"WAVE_HEALTH_VERDICT_UNHEALTHY":   3,
	}
)

func (x WaveHealthVerdict) Enum() *WaveHealthVerdict {
	p := new(WaveHealthVerdict)
	*p = x
	return p
}

func (x WaveHealthVerdict) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WaveHealthVerdict) Descriptor() protoreflect.EnumDescriptor {
	return file_rollout_v1_rollout_proto_enumTypes[0].Descriptor()
}

func (WaveHealthVerdict) Type() protoreflect.EnumType {
	return &file_rollout_v1_rollout_proto_enumTypes[0]
}

func (x WaveHealthVerdict) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WaveHealthVerdict.Descriptor instead.
func (WaveHealthVerdict) EnumDescriptor() ([]byte, []int) {
	return file_rollout_v1_rollout_proto_rawDescGZIP(), []int{0}
}

// GetWaveHealthRequest names the wave to evaluate. Both ids are required: a wave is only
// meaningful inside its rollout, and the pair is what makes the answer unambiguous.
type GetWaveHealthRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Rollout whose wave is evaluated.
	RolloutId string `protobuf:"bytes,1,opt,name=rollout_id,json=rolloutId,proto3" json:"rollout_id,omitempty"`
	// Wave of that rollout to evaluate.
	WaveId        string `protobuf:"bytes,2,opt,name=wave_id,json=waveId,proto3" json:"wave_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWaveHealthRequest) Reset() {
	*x = GetWaveHealthRequest{}
	mi := &file_rollout_v1_rollout_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWaveHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWaveHealthRequest) ProtoMessage() {}

func (x *GetWaveHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rollout_v1_rollout_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWaveHealthRequest.ProtoReflect.Descriptor instead.
func (*GetWaveHealthRequest) Descriptor() ([]byte, []int) {
	return file_rollout_v1_rollout_proto_rawDescGZIP(), []int{0}
}

func (x *GetWaveHealthRequest) GetRolloutId() string {
	if x != nil {
		return x.RolloutId
	}
	return ""
}

func (x *GetWaveHealthRequest) GetWaveId() string {
	if x != nil {
		return x.WaveId
	}
	return ""
}

// GetWaveHealthResponse is one wave's health: the measurement, the evidence behind it, and
// the configuration it was judged against. The verdict is never left unspecified on a served
// response — a window without enough evidence is reported as undecided.
type GetWaveHealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Rollout the evaluation was requested for, echoed so concurrent callers can match
	// results to requests.
	RolloutId string `protobuf:"bytes,1,opt,name=rollout_id,json=rolloutId,proto3" json:"rollout_id,omitempty"`
	// Wave the evaluation was requested for, echoed likewise.
	WaveId string `protobuf:"bytes,2,opt,name=wave_id,json=waveId,proto3" json:"wave_id,omitempty"`
	// Share of the window's samples whose health was at or above the per-sample health
	// threshold, in [0, 1]; zero when the window holds no samples.
	SuccessRatio float64 `protobuf:"fixed64,3,opt,name=success_ratio,json=successRatio,proto3" json:"success_ratio,omitempty"`
	// Number of heartbeat samples the ratio was computed over; zero for an empty window.
	SampleSize int64 `protobuf:"varint,4,opt,name=sample_size,json=sampleSize,proto3" json:"sample_size,omitempty"`
	// Verdict the ratio and sample size produced.
	Verdict WaveHealthVerdict `protobuf:"varint,5,opt,name=verdict,proto3,enum=fleetops.rollout.v1.WaveHealthVerdict" json:"verdict,omitempty"`
	// Start of the effective window the samples were read from: the configured health window
	// ending at the evaluation, never earlier than the wave's start.
	WindowStart *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=window_start,json=windowStart,proto3" json:"window_start,omitempty"`
	// End of the effective window, at the moment the evaluation ran.
	WindowEnd *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=window_end,json=windowEnd,proto3" json:"window_end,omitempty"`
	// Health score at or above which a sample counted as a success.
	SampleHealthThreshold float64 `protobuf:"fixed64,8,opt,name=sample_health_threshold,json=sampleHealthThreshold,proto3" json:"sample_health_threshold,omitempty"`
	// Success ratio at or above which a decided window is healthy.
	MinSuccessRatio float64 `protobuf:"fixed64,9,opt,name=min_success_ratio,json=minSuccessRatio,proto3" json:"min_success_ratio,omitempty"`
	// Sample count a window must hold before its verdict is decided.
	MinSamples    int64 `protobuf:"varint,10,opt,name=min_samples,json=minSamples,proto3" json:"min_samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWaveHealthResponse) Reset() {
	*x = GetWaveHealthResponse{}
	mi := &file_rollout_v1_rollout_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWaveHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWaveHealthResponse) ProtoMessage() {}

func (x *GetWaveHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rollout_v1_rollout_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWaveHealthResponse.ProtoReflect.Descriptor instead.
func (*GetWaveHealthResponse) Descriptor() ([]byte, []int) {
	return file_rollout_v1_rollout_proto_rawDescGZIP(), []int{1}
}

func (x *GetWaveHealthResponse) GetRolloutId() string {
	if x != nil {
		return x.RolloutId
	}
	return ""
}

func (x *GetWaveHealthResponse) GetWaveId() string {
	if x != nil {
		return x.WaveId
	}
	return ""
}

func (x *GetWaveHealthResponse) GetSuccessRatio() float64 {
	if x != nil {
		return x.SuccessRatio
	}
	return 0
}

func (x *GetWaveHealthResponse) GetSampleSize() int64 {
	if x != nil {
		return x.SampleSize
	}
	return 0
}

func (x *GetWaveHealthResponse) GetVerdict() WaveHealthVerdict {
	if x != nil {
		return x.Verdict
	}
	return WaveHealthVerdict_WAVE_HEALTH_VERDICT_UNSPECIFIED
}

func (x *GetWaveHealthResponse) GetWindowStart() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowStart
	}
	return nil
}

func (x *GetWaveHealthResponse) GetWindowEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowEnd
	}
	return nil
}

func (x *GetWaveHealthResponse) GetSampleHealthThreshold() float64 {
	if x != nil {
		return x.SampleHealthThreshold
	}
	return 0
}

func (x *GetWaveHealthResponse) GetMinSuccessRatio() float64 {
	if x != nil {
		return x.MinSuccessRatio
	}
	return 0
}

func (x *GetWaveHealthResponse) GetMinSamples() int64 {
	if x != nil {
		return x.MinSamples
	}
	return 0
}

var File_rollout_v1_rollout_proto protoreflect.FileDescriptor

const file_rollout_v1_rollout_proto_rawDesc = "" +
	"\n" +
	"\x18rollout/v1/rollout.proto\x12\x13fleetops.rollout.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"N\n" +
	"\x14GetWaveHealthRequest\x12\x1d\n" +
	"\n" +
	"rollout_id\x18\x01 \x01(\tR\trolloutId\x12\x17\n" +
	"\awave_id\x18\x02 \x01(\tR\x06waveId\"\xd6\x03\n" +
	"\x15GetWaveHealthResponse\x12\x1d\n" +
	"\n" +
	"rollout_id\x18\x01 \x01(\tR\trolloutId\x12\x17\n" +
	"\awave_id\x18\x02 \x01(\tR\x06waveId\x12#\n" +
	"\rsuccess_ratio\x18\x03 \x01(\x01R\fsuccessRatio\x12\x1f\n" +
	"\vsample_size\x18\x04 \x01(\x03R\n" +
	"sampleSize\x12@\n" +
	"\averdict\x18\x05 \x01(\x0e2&.fleetops.rollout.v1.WaveHealthVerdictR\averdict\x12=\n" +
	"\fwindow_start\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vwindowStart\x129\n" +
	"\n" +
	"window_end\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\twindowEnd\x126\n" +
	"\x17sample_health_threshold\x18\b \x01(\x01R\x15sampleHealthThreshold\x12*\n" +
	"\x11min_success_ratio\x18\t \x01(\x01R\x0fminSuccessRatio\x12\x1f\n" +
	"\vmin_samples\x18\n" +
	" \x01(\x03R\n" +
	"minSamples*\x9f\x01\n" +
	"\x11WaveHealthVerdict\x12#\n" +
	"\x1fWAVE_HEALTH_VERDICT_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dWAVE_HEALTH_VERDICT_UNDECIDED\x10\x01\x12\x1f\n" +
	"\x1bWAVE_HEALTH_VERDICT_HEALTHY\x10\x02\x12!\n" +
	"\x1dWAVE_HEALTH_VERDICT_UNHEALTHY\x10\x032x\n" +
	"\x0eRolloutService\x12f\n" +
	"\rGetWaveHealth\x12).fleetops.rollout.v1.GetWaveHealthRequest\x1a*.fleetops.rollout.v1.GetWaveHealthResponseB>Z<github.com/DisMosGit/fleetops/api/proto/rollout/v1;rolloutv1b\x06proto3"

var (
	file_rollout_v1_rollout_proto_rawDescOnce sync.Once
	file_rollout_v1_rollout_proto_rawDescData []byte
)

func file_rollout_v1_rollout_proto_rawDescGZIP() []byte {
	file_rollout_v1_rollout_proto_rawDescOnce.Do(func() {
		file_rollout_v1_rollout_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rollout_v1_rollout_proto_rawDesc), len(file_rollout_v1_rollout_proto_rawDesc)))
	})
	return file_rollout_v1_rollout_proto_rawDescData
}

var file_rollout_v1_rollout_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rollout_v1_rollout_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rollout_v1_rollout_proto_goTypes = []any{
	(WaveHealthVerdict)(0),        // 0: fleetops.rollout.v1.WaveHealthVerdict
	(*GetWaveHealthRequest)(nil),  // 1: fleetops.rollout.v1.GetWaveHealthRequest
	(*GetWaveHealthResponse)(nil), // 2: fleetops.rollout.v1.GetWaveHealthResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_rollout_v1_rollout_proto_depIdxs = []int32{
	0, // 0: fleetops.rollout.v1.GetWaveHealthResponse.verdict:type_name -> fleetops.rollout.v1.WaveHealthVerdict
	3, // 1: fleetops.rollout.v1.GetWaveHealthResponse.window_start:type_name -> google.protobuf.Timestamp
	3, // 2: fleetops.rollout.v1.GetWaveHealthResponse.window_end:type_name -> google.protobuf.Timestamp
	1, // 3: fleetops.rollout.v1.RolloutService.GetWaveHealth:input_type -> fleetops.rollout.v1.GetWaveHealthRequest
	2, // 4: fleetops.rollout.v1.RolloutService.GetWaveHealth:output_type -> fleetops.rollout.v1.GetWaveHealthResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rollout_v1_rollout_proto_init() }
func file_rollout_v1_rollout_proto_init() {
	if File_rollout_v1_rollout_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rollout_v1_rollout_proto_rawDesc), len(file_rollout_v1_rollout_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rollout_v1_rollout_proto_goTypes,
		DependencyIndexes: file_rollout_v1_rollout_proto_depIdxs,
		EnumInfos:         file_rollout_v1_rollout_proto_enumTypes,
		MessageInfos:      file_rollout_v1_rollout_proto_msgTypes,
	}.Build()
	File_rollout_v1_rollout_proto = out.File
	file_rollout_v1_rollout_proto_goTypes = nil
	file_rollout_v1_rollout_proto_depIdxs = nil
}
