// FleetOps rollout health contract, v1.
//
// One unary RolloutService.GetWaveHealth answers the question a canary gate asks: how
// healthy is a given wave of a given rollout right now, and on how much evidence. The
// response carries the measured success ratio and sample size together with the window the
// samples were read from and the thresholds the verdict was computed against, so a caller
// never has to guess which configuration produced a number.
//
// This package is a different bounded context from the agent transport: an operator health
// query is not an agent exchange, and messages are never shared across the two packages.
//
// v1 freezes when it lands: evolve by adding fields, messages, and RPCs only. Never
// renumber, reuse, or rewrite an existing field.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: rollout/v1/rollout.proto

package rolloutv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RolloutService_GetWaveHealth_FullMethodName = "/fleetops.rollout.v1.RolloutService/GetWaveHealth"
)

// RolloutServiceClient is the client API for RolloutService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RolloutService is the operator- and workflow-facing surface over rollout state: it answers
// how a running canary wave is doing, over the heartbeat telemetry its devices emitted.
type RolloutServiceClient interface {
	// GetWaveHealth evaluates one wave of one rollout over the configured sliding health
	// window and returns the wave's success ratio, the sample size the ratio rests on, and the
	// resulting verdict. An empty window is a successful, undecided result rather than an
	// error; an unknown rollout or a wave that is not that rollout's maps to NOT_FOUND, and a
	// request missing either id is rejected as INVALID_ARGUMENT before any state is read.
	GetWaveHealth(ctx context.Context, in *GetWaveHealthRequest, opts ...grpc.CallOption) (*GetWaveHealthResponse, error)
}

type rolloutServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRolloutServiceClient(cc grpc.ClientConnInterface) RolloutServiceClient {
	return &rolloutServiceClient{cc}
}

func (c *rolloutServiceClient) GetWaveHealth(ctx context.Context, in *GetWaveHealthRequest, opts ...grpc.CallOption) (*GetWaveHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWaveHealthResponse)
	err := c.cc.Invoke(ctx, RolloutService_GetWaveHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RolloutServiceServer is the server API for RolloutService service.
// All implementations must embed UnimplementedRolloutServiceServer
// for forward compatibility.
//
// RolloutService is the operator- and workflow-facing surface over rollout state: it answers
// how a running canary wave is doing, over the heartbeat telemetry its devices emitted.
type RolloutServiceServer interface {
	// GetWaveHealth evaluates one wave of one rollout over the configured sliding health
	// window and returns the wave's success ratio, the sample size the ratio rests on, and the
	// resulting verdict. An empty window is a successful, undecided result rather than an
	// error; an unknown rollout or a wave that is not that rollout's maps to NOT_FOUND, and a
	// request missing either id is rejected as INVALID_ARGUMENT before any state is read.
	GetWaveHealth(context.Context, *GetWaveHealthRequest) (*GetWaveHealthResponse, error)
	mustEmbedUnimplementedRolloutServiceServer()
}

// UnimplementedRolloutServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRolloutServiceServer struct{}

func (UnimplementedRolloutServiceServer) GetWaveHealth(context.Context, *GetWaveHealthRequest) (*GetWaveHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWaveHealth not implemented")
}
func (UnimplementedRolloutServiceServer) mustEmbedUnimplementedRolloutServiceServer() {}
func (UnimplementedRolloutServiceServer) testEmbeddedByValue()                        {}

// UnsafeRolloutServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RolloutServiceServer will
// result in compilation errors.
type UnsafeRolloutServiceServer interface {
	mustEmbedUnimplementedRolloutServiceServer()
}

func RegisterRolloutServiceServer(s grpc.ServiceRegistrar, srv RolloutServiceServer) {
	// If the following call panics, it indicates UnimplementedRolloutServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RolloutService_ServiceDesc, srv)
}

func _RolloutService_GetWaveHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWaveHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolloutServiceServer).GetWaveHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolloutService_GetWaveHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolloutServiceServer).GetWaveHealth(ctx, req.(*GetWaveHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RolloutService_ServiceDesc is the grpc.ServiceDesc for RolloutService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RolloutService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fleetops.rollout.v1.RolloutService",
	HandlerType: (*RolloutServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWaveHealth",
			Handler:    _RolloutService_GetWaveHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rollout/v1/rollout.proto",
}
