// FleetOps agent <-> control-plane wire contract, v1.
//
// One long-lived AgentService.Connect stream per agent carries heartbeats and requests
// inbound and commands and responses outbound; AgentService.Report delivers the terminal
// result of one command over a unary call that accepts an idempotency key.
//
// v1 freezes when it lands: evolve by adding fields, messages, and RPCs only. Never
// renumber, reuse, or rewrite an existing field.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: agent/v1/agent.proto

package agentv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_Connect_FullMethodName          = "/fleetops.agent.v1.AgentService/Connect"
	AgentService_Report_FullMethodName           = "/fleetops.agent.v1.AgentService/Report"
	AgentService_DownloadFirmware_FullMethodName = "/fleetops.agent.v1.AgentService/DownloadFirmware"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService is the control-plane surface every device agent speaks: one bidirectional
// stream for the live conversation (heartbeats up, commands down), one unary call for
// command results that must survive stream loss, and one server stream per firmware download.
type AgentServiceClient interface {
	// Connect is one long-lived bidirectional stream per agent. AgentEnvelope carries
	// registration, heartbeats, and the agent-initiated request/response exchanges;
	// ControlEnvelope carries their responses and the commands. Both directions are
	// correlated instead of ordered: responses echo the correlation id of their request so
	// concurrent exchanges on one stream cannot be mismatched after a reconnect.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentEnvelope, ControlEnvelope], error)
	// Report delivers the terminal result of one command. It carries an idempotency key in
	// addition to the command id because a retried report must never re-trigger the
	// command's effects: a key already seen is accepted again with no second effect, and a
	// report without a key is rejected as INVALID_ARGUMENT.
	Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error)
	// DownloadFirmware streams one firmware binary to the agent as bounded chunks over a
	// server stream. The agent issues it after a StartUpdate command; the stream opens with
	// the metadata message (version, checksum, total size, no chunk), carries the binary in
	// offset-ordered chunks, and closes with the end-of-transfer marker, so neither side ever
	// holds the whole binary in memory. It reuses the firmware download messages of the
	// Connect exchange; that exchange stays frozen and is not served.
	DownloadFirmware(ctx context.Context, in *FirmwareDownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FirmwareDownloadResponse], error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentEnvelope, ControlEnvelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentEnvelope, ControlEnvelope]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ConnectClient = grpc.BidiStreamingClient[AgentEnvelope, ControlEnvelope]

func (c *agentServiceClient) Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, AgentService_Report_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DownloadFirmware(ctx context.Context, in *FirmwareDownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FirmwareDownloadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[1], AgentService_DownloadFirmware_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FirmwareDownloadRequest, FirmwareDownloadResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_DownloadFirmwareClient = grpc.ServerStreamingClient[FirmwareDownloadResponse]

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService is the control-plane surface every device agent speaks: one bidirectional
// stream for the live conversation (heartbeats up, commands down), one unary call for
// command results that must survive stream loss, and one server stream per firmware download.
type AgentServiceServer interface {
	// Connect is one long-lived bidirectional stream per agent. AgentEnvelope carries
	// registration, heartbeats, and the agent-initiated request/response exchanges;
	// ControlEnvelope carries their responses and the commands. Both directions are
	// correlated instead of ordered: responses echo the correlation id of their request so
	// concurrent exchanges on one stream cannot be mismatched after a reconnect.
	Connect(grpc.BidiStreamingServer[AgentEnvelope, ControlEnvelope]) error
	// Report delivers the terminal result of one command. It carries an idempotency key in
	// addition to the command id because a retried report must never re-trigger the
	// command's effects: a key already seen is accepted again with no second effect, and a
	// report without a key is rejected as INVALID_ARGUMENT.
	Report(context.Context, *ReportRequest) (*ReportResponse, error)
	// DownloadFirmware streams one firmware binary to the agent as bounded chunks over a
	// server stream. The agent issues it after a StartUpdate command; the stream opens with
	// the metadata message (version, checksum, total size, no chunk), carries the binary in
	// offset-ordered chunks, and closes with the end-of-transfer marker, so neither side ever
	// holds the whole binary in memory. It reuses the firmware download messages of the
	// Connect exchange; that exchange stays frozen and is not served.
	DownloadFirmware(*FirmwareDownloadRequest, grpc.ServerStreamingServer[FirmwareDownloadResponse]) error
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Connect(grpc.BidiStreamingServer[AgentEnvelope, ControlEnvelope]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedAgentServiceServer) Report(context.Context, *ReportRequest) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Report not implemented")
}
func (UnimplementedAgentServiceServer) DownloadFirmware(*FirmwareDownloadRequest, grpc.ServerStreamingServer[FirmwareDownloadResponse]) error {
	return status.Error(codes.Unimplemented, "method DownloadFirmware not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).Connect(&grpc.GenericServerStream[AgentEnvelope, ControlEnvelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ConnectServer = grpc.BidiStreamingServer[AgentEnvelope, ControlEnvelope]

func _AgentService_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Report(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Report_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Report(ctx, req.(*ReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DownloadFirmware_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FirmwareDownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).DownloadFirmware(m, &grpc.GenericServerStream[FirmwareDownloadRequest, FirmwareDownloadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_DownloadFirmwareServer = grpc.ServerStreamingServer[FirmwareDownloadResponse]

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fleetops.agent.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Report",
			Handler:    _AgentService_Report_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _AgentService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadFirmware",
			Handler:       _AgentService_DownloadFirmware_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent/v1/agent.proto",
}
