// FleetOps agent <-> control-plane wire contract, v1.
//
// One long-lived AgentService.Connect stream per agent carries heartbeats and requests
// inbound and commands and responses outbound; AgentService.Report delivers the terminal
// result of one command over a unary call that accepts an idempotency key.
//
// v1 freezes when it lands: evolve by adding fields, messages, and RPCs only. Never
// renumber, reuse, or rewrite an existing field.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: agent/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UpdatePhase names where a device is in the firmware update lifecycle, including the two
// terminal failure paths the rollout saga acts on.
type UpdatePhase int32

const (
	// Unset; rejected by the control plane as an invalid phase.
	UpdatePhase_UPDATE_PHASE_UNSPECIFIED UpdatePhase = 0
	// Firmware binary is being downloaded and verified.
	UpdatePhase_UPDATE_PHASE_DOWNLOADING UpdatePhase = 1
	// Firmware is being applied to the device.
	UpdatePhase_UPDATE_PHASE_APPLYING UpdatePhase = 2
	// Device is rebooting into the new firmware.
	UpdatePhase_UPDATE_PHASE_REBOOTING UpdatePhase = 3
	// Update finished and the device runs the new firmware.
	UpdatePhase_UPDATE_PHASE_COMPLETED UpdatePhase = 4
	// Update failed; detail on the request names why.
	UpdatePhase_UPDATE_PHASE_FAILED UpdatePhase = 5
	// Device was rolled back to its previous firmware.
	UpdatePhase_UPDATE_PHASE_ROLLED_BACK UpdatePhase = 6
)

// Enum value maps for UpdatePhase.
var (
	UpdatePhase_name = map[int32]string{
		0: "UPDATE_PHASE_UNSPECIFIED",
		1: "UPDATE_PHASE_DOWNLOADING",
		2: "UPDATE_PHASE_APPLYING",
		3: "UPDATE_PHASE_REBOOTING",
		4: "UPDATE_PHASE_COMPLETED",
		5: "UPDATE_PHASE_FAILED",
		6: "UPDATE_PHASE_ROLLED_BACK",
	}
	UpdatePhase_value = map[string]int32{
		"UPDATE_PHASE_UNSPECIFIED": 0,
		"UPDATE_PHASE_DOWNLOADING": 1,
		"UPDATE_PHASE_APPLYING":    2,
		"UPDATE_PHASE_REBOOTING":   3,
		"UPDATE_PHASE_COMPLETED":   4,
		"UPDATE_PHASE_FAILED":      5,
		"UPDATE_PHASE_ROLLED_BACK": 6,
	}
)

func (x UpdatePhase) Enum() *UpdatePhase {
	p := new(UpdatePhase)
	*p = x
	return p
}

func (x UpdatePhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdatePhase) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_v1_agent_proto_enumTypes[0].Descriptor()
}

func (UpdatePhase) Type() protoreflect.EnumType {
	return &file_agent_v1_agent_proto_enumTypes[0]
}

func (x UpdatePhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdatePhase.Descriptor instead.
func (UpdatePhase) EnumDescriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

// CommandOutcome names the terminal state of one command, as reported through Report.
type CommandOutcome int32

const (
	// Unset; rejected by the control plane as an invalid outcome.
	CommandOutcome_COMMAND_OUTCOME_UNSPECIFIED CommandOutcome = 0
	// Command completed; the device reached the commanded state.
	CommandOutcome_COMMAND_OUTCOME_SUCCEEDED CommandOutcome = 1
	// Command did not complete; detail on the request names why.
	CommandOutcome_COMMAND_OUTCOME_FAILED CommandOutcome = 2
)

// Enum value maps for CommandOutcome.
var (
	CommandOutcome_name = map[int32]string{
		0: "COMMAND_OUTCOME_UNSPECIFIED",
		1: "COMMAND_OUTCOME_SUCCEEDED",
		2: "COMMAND_OUTCOME_FAILED",
	}
	CommandOutcome_value = map[string]int32{
		"COMMAND_OUTCOME_UNSPECIFIED": 0,
		"COMMAND_OUTCOME_SUCCEEDED":   1,
		"COMMAND_OUTCOME_FAILED":      2,
	}
)

func (x CommandOutcome) Enum() *CommandOutcome {
	p := new(CommandOutcome)
	*p = x
	return p
}

func (x CommandOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_v1_agent_proto_enumTypes[1].Descriptor()
}

func (CommandOutcome) Type() protoreflect.EnumType {
	return &file_agent_v1_agent_proto_enumTypes[1]
}

func (x CommandOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandOutcome.Descriptor instead.
func (CommandOutcome) EnumDescriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

// AgentEnvelope is one message from agent to control plane on the Connect stream. The
// correlation id is set on requests that expect a response and left empty on fire-and-forget
// messages such as heartbeats.
type AgentEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Correlation id echoed by the response to this request; empty for heartbeats.
	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// The carried message; exactly one payload per envelope.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentEnvelope_RegisterDevice
	//	*AgentEnvelope_Heartbeat
	//	*AgentEnvelope_FirmwareDownload
	//	*AgentEnvelope_UpdateStatus
	Payload       isAgentEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEnvelope) Reset() {
	*x = AgentEnvelope{}
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEnvelope) ProtoMessage() {}

func (x *AgentEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEnvelope.ProtoReflect.Descriptor instead.
func (*AgentEnvelope) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentEnvelope) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AgentEnvelope) GetPayload() isAgentEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentEnvelope) GetRegisterDevice() *RegisterDeviceRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentEnvelope_RegisterDevice); ok {
			return x.RegisterDevice
		}
	}
	return nil
}

func (x *AgentEnvelope) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentEnvelope_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentEnvelope) GetFirmwareDownload() *FirmwareDownloadRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentEnvelope_FirmwareDownload); ok {
			return x.FirmwareDownload
		}
	}
	return nil
}

func (x *AgentEnvelope) GetUpdateStatus() *UpdateStatusRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentEnvelope_UpdateStatus); ok {
			return x.UpdateStatus
		}
	}
	return nil
}

type isAgentEnvelope_Payload interface {
	isAgentEnvelope_Payload()
}

type AgentEnvelope_RegisterDevice struct {
	// Registration of a device behind this agent; expects a RegisterDeviceResponse.
	RegisterDevice *RegisterDeviceRequest `protobuf:"bytes,2,opt,name=register_device,json=registerDevice,proto3,oneof"`
}

type AgentEnvelope_Heartbeat struct {
	// Fire-and-forget device heartbeat; no response is sent.
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type AgentEnvelope_FirmwareDownload struct {
	// Firmware binary pull; expects chunked FirmwareDownloadResponse messages.
	FirmwareDownload *FirmwareDownloadRequest `protobuf:"bytes,4,opt,name=firmware_download,json=firmwareDownload,proto3,oneof"`
}

type AgentEnvelope_UpdateStatus struct {
	// Firmware update progress report; expects an UpdateStatusResponse.
	UpdateStatus *UpdateStatusRequest `protobuf:"bytes,5,opt,name=update_status,json=updateStatus,proto3,oneof"`
}

func (*AgentEnvelope_RegisterDevice) isAgentEnvelope_Payload() {}

func (*AgentEnvelope_Heartbeat) isAgentEnvelope_Payload() {}

func (*AgentEnvelope_FirmwareDownload) isAgentEnvelope_Payload() {}

func (*AgentEnvelope_UpdateStatus) isAgentEnvelope_Payload() {}

// ControlEnvelope is one message from control plane to agent on the Connect stream. It
// carries either the response to an agent request (under the request's correlation id) or a
// command (under its own command id).
type ControlEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Correlation id of the request being answered; empty for commands.
	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// The carried message; exactly one payload per envelope.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*ControlEnvelope_RegisterDevice
	//	*ControlEnvelope_FirmwareDownload
	//	*ControlEnvelope_UpdateStatus
	//	*ControlEnvelope_Command
	Payload       isControlEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlEnvelope) Reset() {
	*x = ControlEnvelope{}
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlEnvelope) ProtoMessage() {}

func (x *ControlEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlEnvelope.ProtoReflect.Descriptor instead.
func (*ControlEnvelope) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ControlEnvelope) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ControlEnvelope) GetPayload() isControlEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControlEnvelope) GetRegisterDevice() *RegisterDeviceResponse {
	if x != nil {
		if x, ok := x.Payload.(*ControlEnvelope_RegisterDevice); ok {
			return x.RegisterDevice
		}
	}
	return nil
}

func (x *ControlEnvelope) GetFirmwareDownload() *FirmwareDownloadResponse {
	if x != nil {
		if x, ok := x.Payload.(*ControlEnvelope_FirmwareDownload); ok {
			return x.FirmwareDownload
		}
	}
	return nil
}

func (x *ControlEnvelope) GetUpdateStatus() *UpdateStatusResponse {
	if x != nil {
		if x, ok := x.Payload.(*ControlEnvelope_UpdateStatus); ok {
			return x.UpdateStatus
		}
	}
	return nil
}

func (x *ControlEnvelope) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Payload.(*ControlEnvelope_Command); ok {
			return x.Command
		}
	}
	return nil
}

type isControlEnvelope_Payload interface {
	isControlEnvelope_Payload()
}

type ControlEnvelope_RegisterDevice struct {
	// Acceptance decision for a registration.
	RegisterDevice *RegisterDeviceResponse `protobuf:"bytes,2,opt,name=register_device,json=registerDevice,proto3,oneof"`
}

type ControlEnvelope_FirmwareDownload struct {
	// One chunk (or the end marker) of a firmware transfer.
	FirmwareDownload *FirmwareDownloadResponse `protobuf:"bytes,3,opt,name=firmware_download,json=firmwareDownload,proto3,oneof"`
}

type ControlEnvelope_UpdateStatus struct {
	// Acknowledgment of an update status report.
	UpdateStatus *UpdateStatusResponse `protobuf:"bytes,4,opt,name=update_status,json=updateStatus,proto3,oneof"`
}

type ControlEnvelope_Command struct {
	// A command for a device behind this agent.
	Command *Command `protobuf:"bytes,5,opt,name=command,proto3,oneof"`
}

func (*ControlEnvelope_RegisterDevice) isControlEnvelope_Payload() {}

func (*ControlEnvelope_FirmwareDownload) isControlEnvelope_Payload() {}

func (*ControlEnvelope_UpdateStatus) isControlEnvelope_Payload() {}

func (*ControlEnvelope_Command) isControlEnvelope_Payload() {}

// RegisterDeviceRequest enrols a device on the stream before commands may target it. Its
// identity fields mirror the device record so ingestion is a mapping, not a translation.
type RegisterDeviceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable device identity; the key of the device record.
	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Device model, part of the rollout target group.
	Model string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	// Device region, part of the rollout target group.
	Region string `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	// Firmware version the device currently runs (current_fw).
	CurrentFw     string `protobuf:"bytes,4,opt,name=current_fw,json=currentFw,proto3" json:"current_fw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceRequest) Reset() {
	*x = RegisterDeviceRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceRequest) ProtoMessage() {}

func (x *RegisterDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceRequest.ProtoReflect.Descriptor instead.
func (*RegisterDeviceRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RegisterDeviceRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *RegisterDeviceRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RegisterDeviceRequest) GetCurrentFw() string {
	if x != nil {
		return x.CurrentFw
	}
	return ""
}

// RegisterDeviceResponse answers a registration with the control plane's decision. A
// rejection never creates a device record; reason is operator-safe detail only.
type RegisterDeviceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the device was accepted into the fleet.
	Accepted bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// Identity echoed so the agent can match the answer to its request.
	DeviceId string `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Resulting device status after the decision.
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// Operator-safe reason set when accepted is false.
	Reason        string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceResponse) Reset() {
	*x = RegisterDeviceResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceResponse) ProtoMessage() {}

func (x *RegisterDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceResponse.ProtoReflect.Descriptor instead.
func (*RegisterDeviceResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterDeviceResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterDeviceResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RegisterDeviceResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RegisterDeviceResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Heartbeat is one liveness and health sample from a device. Its fields are exactly one
// telemetry event plus the device-state fields, and event_id makes redelivery after a
// reconnect idempotent for ingestion.
type Heartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique id of this heartbeat event; a redelivery reuses the same id.
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Device the sample belongs to.
	DeviceId string `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Firmware version the device currently runs (current_fw).
	CurrentFw string `protobuf:"bytes,3,opt,name=current_fw,json=currentFw,proto3" json:"current_fw,omitempty"`
	// Reported device status.
	Status string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	// Sample time, keyed as ts in telemetry storage.
	Ts *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=ts,proto3" json:"ts,omitempty"`
	// CPU utilisation sample.
	Cpu float64 `protobuf:"fixed64,6,opt,name=cpu,proto3" json:"cpu,omitempty"`
	// Memory utilisation sample.
	Mem float64 `protobuf:"fixed64,7,opt,name=mem,proto3" json:"mem,omitempty"`
	// Health score sample driving wave gates.
	Health        float64 `protobuf:"fixed64,8,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Heartbeat) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Heartbeat) GetCurrentFw() string {
	if x != nil {
		return x.CurrentFw
	}
	return ""
}

func (x *Heartbeat) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Heartbeat) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Heartbeat) GetCpu() float64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *Heartbeat) GetMem() float64 {
	if x != nil {
		return x.Mem
	}
	return 0
}

func (x *Heartbeat) GetHealth() float64 {
	if x != nil {
		return x.Health
	}
	return 0
}

// FirmwareDownloadRequest pulls a firmware binary by id. The agent issues it after a
// StartUpdate command and assembles the chunks returned on the same correlation id.
type FirmwareDownloadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device that will apply the firmware.
	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Firmware identity to fetch.
	FirmwareId    string `protobuf:"bytes,2,opt,name=firmware_id,json=firmwareId,proto3" json:"firmware_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirmwareDownloadRequest) Reset() {
	*x = FirmwareDownloadRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirmwareDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirmwareDownloadRequest) ProtoMessage() {}

func (x *FirmwareDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirmwareDownloadRequest.ProtoReflect.Descriptor instead.
func (*FirmwareDownloadRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *FirmwareDownloadRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *FirmwareDownloadRequest) GetFirmwareId() string {
	if x != nil {
		return x.FirmwareId
	}
	return ""
}

// FirmwareDownloadResponse carries one bounded chunk of a firmware binary. Metadata and the
// checksum are present independently of the chunk stream so the agent can verify what it
// assembles; transfer ends when eof is true.
type FirmwareDownloadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Firmware identity being transferred.
	FirmwareId string `protobuf:"bytes,1,opt,name=firmware_id,json=firmwareId,proto3" json:"firmware_id,omitempty"`
	// Firmware version being transferred.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Checksum of the complete binary, for the agent to verify the assembly.
	Checksum string `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	// One bounded-size piece of the binary; empty on a metadata-only or eof message.
	Chunk []byte `protobuf:"bytes,4,opt,name=chunk,proto3" json:"chunk,omitempty"`
	// Byte offset of this chunk within the complete binary.
	Offset int64 `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	// End-of-transfer marker: true on the final message of the download.
	Eof           bool `protobuf:"varint,6,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirmwareDownloadResponse) Reset() {
	*x = FirmwareDownloadResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirmwareDownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirmwareDownloadResponse) ProtoMessage() {}

func (x *FirmwareDownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirmwareDownloadResponse.ProtoReflect.Descriptor instead.
func (*FirmwareDownloadResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *FirmwareDownloadResponse) GetFirmwareId() string {
	if x != nil {
		return x.FirmwareId
	}
	return ""
}

func (x *FirmwareDownloadResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *FirmwareDownloadResponse) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *FirmwareDownloadResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *FirmwareDownloadResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FirmwareDownloadResponse) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

// UpdateStatusRequest reports firmware-update progress for one device. Fine-grained and
// frequent, it travels on the stream; the terminal command result goes through Report.
type UpdateStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device whose update is progressing.
	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Firmware being applied.
	FirmwareId string `protobuf:"bytes,2,opt,name=firmware_id,json=firmwareId,proto3" json:"firmware_id,omitempty"`
	// Phase the device has reached.
	Phase UpdatePhase `protobuf:"varint,3,opt,name=phase,proto3,enum=fleetops.agent.v1.UpdatePhase" json:"phase,omitempty"`
	// Completion of the current update, 0-100.
	ProgressPercent int32 `protobuf:"varint,4,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	// Operator-safe failure detail; set when phase is UPDATE_PHASE_FAILED.
	Detail        string `protobuf:"bytes,5,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateStatusRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *UpdateStatusRequest) GetFirmwareId() string {
	if x != nil {
		return x.FirmwareId
	}
	return ""
}

func (x *UpdateStatusRequest) GetPhase() UpdatePhase {
	if x != nil {
		return x.Phase
	}
	return UpdatePhase_UPDATE_PHASE_UNSPECIFIED
}

func (x *UpdateStatusRequest) GetProgressPercent() int32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *UpdateStatusRequest) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// UpdateStatusResponse acknowledges an update status report on its correlation id.
type UpdateStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the report was accepted for recording.
	Accepted      bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusResponse) Reset() {
	*x = UpdateStatusResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusResponse) ProtoMessage() {}

func (x *UpdateStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateStatusResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateStatusResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

// Command is one imperative from the control plane to a device, delivered on the stream.
// The device answers with its terminal result through Report, referencing command_id.
type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique id of this command; referenced by the Report that concludes it.
	CommandId string `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// Device the command targets; one agent may front several devices.
	DeviceId string `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// The commanded action; exactly one per command.
	//
	// Types that are valid to be assigned to Kind:
	//
	//	*Command_StartUpdate
	//	*Command_AbortUpdate
	Kind          isCommand_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *Command) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Command) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Command) GetKind() isCommand_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Command) GetStartUpdate() *StartUpdate {
	if x != nil {
		if x, ok := x.Kind.(*Command_StartUpdate); ok {
			return x.StartUpdate
		}
	}
	return nil
}

func (x *Command) GetAbortUpdate() *AbortUpdate {
	if x != nil {
		if x, ok := x.Kind.(*Command_AbortUpdate); ok {
			return x.AbortUpdate
		}
	}
	return nil
}

type isCommand_Kind interface {
	isCommand_Kind()
}

type Command_StartUpdate struct {
	// Begin the download-and-apply cycle for a firmware version.
	StartUpdate *StartUpdate `protobuf:"bytes,3,opt,name=start_update,json=startUpdate,proto3,oneof"`
}

type Command_AbortUpdate struct {
	// Stop a running update.
	AbortUpdate *AbortUpdate `protobuf:"bytes,4,opt,name=abort_update,json=abortUpdate,proto3,oneof"`
}

func (*Command_StartUpdate) isCommand_Kind() {}

func (*Command_AbortUpdate) isCommand_Kind() {}

// StartUpdate commands a device to download (per FirmwareDownloadRequest) and apply the
// named firmware. A rollback downgrade is the same command for the older version.
type StartUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Firmware identity to download and apply.
	FirmwareId string `protobuf:"bytes,1,opt,name=firmware_id,json=firmwareId,proto3" json:"firmware_id,omitempty"`
	// Firmware version expected after the update.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Checksum the downloaded binary must match before applying.
	Checksum      string `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartUpdate) Reset() {
	*x = StartUpdate{}
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartUpdate) ProtoMessage() {}

func (x *StartUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartUpdate.ProtoReflect.Descriptor instead.
func (*StartUpdate) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *StartUpdate) GetFirmwareId() string {
	if x != nil {
		return x.FirmwareId
	}
	return ""
}

func (x *StartUpdate) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StartUpdate) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

// AbortUpdate commands a device to stop a running update at a safe point.
type AbortUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operator-safe reason for the abort.
	Reason        string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortUpdate) Reset() {
	*x = AbortUpdate{}
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortUpdate) ProtoMessage() {}

func (x *AbortUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortUpdate.ProtoReflect.Descriptor instead.
func (*AbortUpdate) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *AbortUpdate) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ReportRequest carries the terminal result of one command. The idempotency key makes
// redelivery of the same result a no-op rather than a second effect.
type ReportRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Idempotency key; identical for every redelivery of this result. Required.
	IdempotencyKey string `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Command being concluded.
	CommandId string `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// Device that executed the command.
	DeviceId string `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Terminal outcome of the command.
	Outcome CommandOutcome `protobuf:"varint,4,opt,name=outcome,proto3,enum=fleetops.agent.v1.CommandOutcome" json:"outcome,omitempty"`
	// Operator-safe failure detail; set when outcome is COMMAND_OUTCOME_FAILED.
	Detail        string `protobuf:"bytes,5,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRequest) Reset() {
	*x = ReportRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRequest) ProtoMessage() {}

func (x *ReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRequest.ProtoReflect.Descriptor instead.
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ReportRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ReportRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ReportRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ReportRequest) GetOutcome() CommandOutcome {
	if x != nil {
		return x.Outcome
	}
	return CommandOutcome_COMMAND_OUTCOME_UNSPECIFIED
}

func (x *ReportRequest) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// ReportResponse states whether the command result was accepted. A report repeating a seen
// idempotency key is accepted too, but produces no second effect.
type ReportResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the result was accepted for processing.
	Accepted      bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ReportResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_agent_v1_agent_proto protoreflect.FileDescriptor

const file_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14agent/v1/agent.proto\x12\x11fleetops.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfe\x02\n" +
	"\rAgentEnvelope\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12S\n" +
	"\x0fregister_device\x18\x02 \x01(\v2(.fleetops.agent.v1.RegisterDeviceRequestH\x00R\x0eregisterDevice\x12<\n" +
	"\theartbeat\x18\x03 \x01(\v2\x1c.fleetops.agent.v1.HeartbeatH\x00R\theartbeat\x12Y\n" +
	"\x11firmware_download\x18\x04 \x01(\v2*.fleetops.agent.v1.FirmwareDownloadRequestH\x00R\x10firmwareDownload\x12M\n" +
	"\rupdate_status\x18\x05 \x01(\v2&.fleetops.agent.v1.UpdateStatusRequestH\x00R\fupdateStatusB\t\n" +
	"\apayload\"\xfd\x02\n" +
	"\x0fControlEnvelope\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12T\n" +
	"\x0fregister_device\x18\x02 \x01(\v2).fleetops.agent.v1.RegisterDeviceResponseH\x00R\x0eregisterDevice\x12Z\n" +
	"\x11firmware_download\x18\x03 \x01(\v2+.fleetops.agent.v1.FirmwareDownloadResponseH\x00R\x10firmwareDownload\x12N\n" +
	"\rupdate_status\x18\x04 \x01(\v2'.fleetops.agent.v1.UpdateStatusResponseH\x00R\fupdateStatus\x126\n" +
	"\acommand\x18\x05 \x01(\v2\x1a.fleetops.agent.v1.CommandH\x00R\acommandB\t\n" +
	"\apayload\"\x81\x01\n" +
	"\x15RegisterDeviceRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x1d\n" +
	"\n" +
	"current_fw\x18\x04 \x01(\tR\tcurrentFw\"\x81\x01\n" +
	"\x16RegisterDeviceResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\xe2\x01\n" +
	"\tHeartbeat\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"current_fw\x18\x03 \x01(\tR\tcurrentFw\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12*\n" +
	"\x02ts\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x10\n" +
	"\x03cpu\x18\x06 \x01(\x01R\x03cpu\x12\x10\n" +
	"\x03mem\x18\a \x01(\x01R\x03mem\x12\x16\n" +
	"\x06health\x18\b \x01(\x01R\x06health\"W\n" +
	"\x17FirmwareDownloadRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vfirmware_id\x18\x02 \x01(\tR\n" +
	"firmwareId\"\xb1\x01\n" +
	"\x18FirmwareDownloadResponse\x12\x1f\n" +
	"\vfirmware_id\x18\x01 \x01(\tR\n" +
	"firmwareId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\tR\bchecksum\x12\x14\n" +
	"\x05chunk\x18\x04 \x01(\fR\x05chunk\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x03R\x06offset\x12\x10\n" +
	"\x03eof\x18\x06 \x01(\bR\x03eof\"\xcc\x01\n" +
	"\x13UpdateStatusRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vfirmware_id\x18\x02 \x01(\tR\n" +
	"firmwareId\x124\n" +
	"\x05phase\x18\x03 \x01(\x0e2\x1e.fleetops.agent.v1.UpdatePhaseR\x05phase\x12)\n" +
	"\x10progress_percent\x18\x04 \x01(\x05R\x0fprogressPercent\x12\x16\n" +
	"\x06detail\x18\x05 \x01(\tR\x06detail\"2\n" +
	"\x14UpdateStatusResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"\xd7\x01\n" +
	"\aCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12C\n" +
	"\fstart_update\x18\x03 \x01(\v2\x1e.fleetops.agent.v1.StartUpdateH\x00R\vstartUpdate\x12C\n" +
	"\fabort_update\x18\x04 \x01(\v2\x1e.fleetops.agent.v1.AbortUpdateH\x00R\vabortUpdateB\x06\n" +
	"\x04kind\"d\n" +
	"\vStartUpdate\x12\x1f\n" +
	"\vfirmware_id\x18\x01 \x01(\tR\n" +
	"firmwareId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\tR\bchecksum\"%\n" +
	"\vAbortUpdate\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\xc9\x01\n" +
	"\rReportRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12;\n" +
	"\aoutcome\x18\x04 \x01(\x0e2!.fleetops.agent.v1.CommandOutcomeR\aoutcome\x12\x16\n" +
	"\x06detail\x18\x05 \x01(\tR\x06detail\",\n" +
	"\x0eReportResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted*\xd3\x01\n" +
	"\vUpdatePhase\x12\x1c\n" +
	"\x18UPDATE_PHASE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18UPDATE_PHASE_DOWNLOADING\x10\x01\x12\x19\n" +
	"\x15UPDATE_PHASE_APPLYING\x10\x02\x12\x1a\n" +
	"\x16UPDATE_PHASE_REBOOTING\x10\x03\x12\x1a\n" +
	"\x16UPDATE_PHASE_COMPLETED\x10\x04\x12\x17\n" +
	"\x13UPDATE_PHASE_FAILED\x10\x05\x12\x1c\n" +
	"\x18UPDATE_PHASE_ROLLED_BACK\x10\x06*l\n" +
	"\x0eCommandOutcome\x12\x1f\n" +
	"\x1bCOMMAND_OUTCOME_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19COMMAND_OUTCOME_SUCCEEDED\x10\x01\x12\x1a\n" +
	"\x16COMMAND_OUTCOME_FAILED\x10\x022\xb2\x01\n" +
	"\fAgentService\x12S\n" +
	"\aConnect\x12 .fleetops.agent.v1.AgentEnvelope\x1a\".fleetops.agent.v1.ControlEnvelope(\x010\x01\x12M\n" +
	"\x06Report\x12 .fleetops.agent.v1.ReportRequest\x1a!.fleetops.agent.v1.ReportResponseB:Z8github.com/DisMosGit/fleetops/api/proto/agent/v1;agentv1b\x06proto3"

var (
	file_agent_v1_agent_proto_rawDescOnce sync.Once
	file_agent_v1_agent_proto_rawDescData []byte
)

func file_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)))
	})
	return file_agent_v1_agent_proto_rawDescData
}

var file_agent_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_agent_v1_agent_proto_goTypes = []any{
	(UpdatePhase)(0),                 // 0: fleetops.agent.v1.UpdatePhase
	(CommandOutcome)(0),              // 1: fleetops.agent.v1.CommandOutcome
	(*AgentEnvelope)(nil),            // 2: fleetops.agent.v1.AgentEnvelope
	(*ControlEnvelope)(nil),          // 3: fleetops.agent.v1.ControlEnvelope
	(*RegisterDeviceRequest)(nil),    // 4: fleetops.agent.v1.RegisterDeviceRequest
	(*RegisterDeviceResponse)(nil),   // 5: fleetops.agent.v1.RegisterDeviceResponse
	(*Heartbeat)(nil),                // 6: fleetops.agent.v1.Heartbeat
	(*FirmwareDownloadRequest)(nil),  // 7: fleetops.agent.v1.FirmwareDownloadRequest
	(*FirmwareDownloadResponse)(nil), // 8: fleetops.agent.v1.FirmwareDownloadResponse
	(*UpdateStatusRequest)(nil),      // 9: fleetops.agent.v1.UpdateStatusRequest
	(*UpdateStatusResponse)(nil),     // 10: fleetops.agent.v1.UpdateStatusResponse
	(*Command)(nil),                  // 11: fleetops.agent.v1.Command
	(*StartUpdate)(nil),              // 12: fleetops.agent.v1.StartUpdate
	(*AbortUpdate)(nil),              // 13: fleetops.agent.v1.AbortUpdate
	(*ReportRequest)(nil),            // 14: fleetops.agent.v1.ReportRequest
	(*ReportResponse)(nil),           // 15: fleetops.agent.v1.ReportResponse
	(*timestamppb.Timestamp)(nil),    // 16: google.protobuf.Timestamp
}
var file_agent_v1_agent_proto_depIdxs = []int32{
	4,  // 0: fleetops.agent.v1.AgentEnvelope.register_device:type_name -> fleetops.agent.v1.RegisterDeviceRequest
	6,  // 1: fleetops.agent.v1.AgentEnvelope.heartbeat:type_name -> fleetops.agent.v1.Heartbeat
	7,  // 2: fleetops.agent.v1.AgentEnvelope.firmware_download:type_name -> fleetops.agent.v1.FirmwareDownloadRequest
	9,  // 3: fleetops.agent.v1.AgentEnvelope.update_status:type_name -> fleetops.agent.v1.UpdateStatusRequest
	5,  // 4: fleetops.agent.v1.ControlEnvelope.register_device:type_name -> fleetops.agent.v1.RegisterDeviceResponse
	8,  // 5: fleetops.agent.v1.ControlEnvelope.firmware_download:type_name -> fleetops.agent.v1.FirmwareDownloadResponse
	10, // 6: fleetops.agent.v1.ControlEnvelope.update_status:type_name -> fleetops.agent.v1.UpdateStatusResponse
	11, // 7: fleetops.agent.v1.ControlEnvelope.command:type_name -> fleetops.agent.v1.Command
	16, // 8: fleetops.agent.v1.Heartbeat.ts:type_name -> google.protobuf.Timestamp
	0,  // 9: fleetops.agent.v1.UpdateStatusRequest.phase:type_name -> fleetops.agent.v1.UpdatePhase
	12, // 10: fleetops.agent.v1.Command.start_update:type_name -> fleetops.agent.v1.StartUpdate
	13, // 11: fleetops.agent.v1.Command.abort_update:type_name -> fleetops.agent.v1.AbortUpdate
	1,  // 12: fleetops.agent.v1.ReportRequest.outcome:type_name -> fleetops.agent.v1.CommandOutcome
	2,  // 13: fleetops.agent.v1.AgentService.Connect:input_type -> fleetops.agent.v1.AgentEnvelope
	14, // 14: fleetops.agent.v1.AgentService.Report:input_type -> fleetops.agent.v1.ReportRequest
	3,  // 15: fleetops.agent.v1.AgentService.Connect:output_type -> fleetops.agent.v1.ControlEnvelope
	15, // 16: fleetops.agent.v1.AgentService.Report:output_type -> fleetops.agent.v1.ReportResponse
	15, // [15:17] is the sub-list for method output_type
	13, // [13:15] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_agent_v1_agent_proto_init() }
func file_agent_v1_agent_proto_init() {
	if File_agent_v1_agent_proto != nil {
		return
	}
	file_agent_v1_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentEnvelope_RegisterDevice)(nil),
		(*AgentEnvelope_Heartbeat)(nil),
		(*AgentEnvelope_FirmwareDownload)(nil),
		(*AgentEnvelope_UpdateStatus)(nil),
	}
	file_agent_v1_agent_proto_msgTypes[1].OneofWrappers = []any{
		(*ControlEnvelope_RegisterDevice)(nil),
		(*ControlEnvelope_FirmwareDownload)(nil),
		(*ControlEnvelope_UpdateStatus)(nil),
		(*ControlEnvelope_Command)(nil),
	}
	file_agent_v1_agent_proto_msgTypes[9].OneofWrappers = []any{
		(*Command_StartUpdate)(nil),
		(*Command_AbortUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_agent_v1_agent_proto_depIdxs,
		EnumInfos:         file_agent_v1_agent_proto_enumTypes,
		MessageInfos:      file_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_agent_v1_agent_proto = out.File
	file_agent_v1_agent_proto_goTypes = nil
	file_agent_v1_agent_proto_depIdxs = nil
}
